name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  xml: ^6.6.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  collection: ^1.19.1
  path: ^1.9.1

  # Hive dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.3
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  flutter_launcher_icons: any

  # Hive generator
  build_runner: ^2.4.13
  hive_generator: any
  json_serializable: any
  analyzer: ^6.4.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
