
name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  xml: ^6.6.1
  path_provider: ^2.1.5
  json_annotation: ^4.8.1 # Aligned version
  intl: ^0.20.2
  collection: ^1.19.1
  path: ^1.9.1
  flutter_riverpod: ^2.6.1

  # Isar dependencies
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: '6.7.1' # Pinned for compatibility
  build_runner: '2.4.9' # Pinned for compatibility
  flutter_launcher_icons: ^0.13.1 # Downgraded as suggested by pub tool

  # Isar generator
  isar_generator: '3.1.0+1' # Pinned for compatibility

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
